define = {
	3: {
		"name":"Mikazuki Munechika",
		"type":"Tachi",
		"survival":"63",
		"impact":"72",
		"leadership":"72",
		"mobility":"37",
		"impulse":"55",
		"loyalty":"30",
		"scouting":"38",
		"camouflage":"35",
	},
	5: {
		"name":"Kogitsunemaru",
		"type":"Tachi",
		"survival":"58",
		"impact":"68",
		"leadership":"69",
		"mobility":"41",
		"impulse":"53",
		"loyalty":"28",
		"scouting":"38",
		"camouflage":"30",
	},
	7: {
		"name":"Ishikirimaru",
		"type":"Oodachi",
		"survival":"72",
		"impact":"85",
		"leadership":"68",
		"mobility":"13",
		"impulse":"61",
		"loyalty":"32",
		"scouting":"15",
		"camouflage":"23",
	},
	9: {
		"name":"Iwatooshi",
		"type":"Naginata",
		"survival":"60",
		"impact":"68",
		"leadership":"51",
		"mobility":"42",
		"impulse":"61",
		"loyalty":"29",
		"scouting":"41",
		"camouflage":"35",
	},
	11: {
		"name":"Imanotsurugi",
		"type":"Tantou",
		"survival":"33",
		"impact":"26",
		"leadership":"38",
		"mobility":"58",
		"impulse":"31",
		"loyalty":"45",
		"scouting":"49",
		"camouflage":"40",
	},
	12: {
		"name":"Imanotsurugi Kiwame",
		"type":"Tantou",
		"survival":"50",
		"impact":"80",
		"leadership":"82",
		"mobility":"142",
		"impulse":"35",
		"loyalty":"60",
		"scouting":"120",
		"camouflage":"109",
	},
	13: {
		"name":"Oodenta Mitsuyo",
		"type":"Tachi",
		"survival":"70",
		"impact":"76",
		"leadership":"70",
		"mobility":"35",
		"impulse":"52",
		"loyalty":"37",
		"scouting":"30",
		"camouflage":"27",
	},
	15: {
		"name":"Sohayanotsurugi",
		"type":"Tachi",
		"survival":"61",
		"impact":"70",
		"leadership":"72",
		"mobility":"48",
		"impulse":"49",
		"loyalty":"25",
		"scouting":"32",
		"camouflage":"31",
	},
	17: {
		"name":"Juzumaru Tsunetsugu",
		"type":"Tachi",
		"survival":"71",
		"impact":"62",
		"leadership":"78",
		"mobility":"38",
		"impulse":"52",
		"loyalty":"29",
		"scouting":"34",
		"camouflage":"30",
	},
	19: {
		"name":"Nikkari Aoe",
		"type":"Wakizashi",
		"survival":"39",
		"impact":"44",
		"leadership":"46",
		"mobility":"52",
		"impulse":"41",
		"loyalty":"40",
		"scouting":"55",
		"camouflage":"45",
	},
	23: {
		"name":"Nakigitsune",
		"type":"Uchigatana",
		"survival":"48",
		"impact":"58",
		"leadership":"50",
		"mobility":"51",
		"impulse":"53",
		"loyalty":"35",
		"scouting":"46",
		"camouflage":"41",
	},
	25: {
		"name":"Ichigo Hitofuri",
		"type":"Tachi",
		"survival":"61",
		"impact":"70",
		"leadership":"72",
		"mobility":"36",
		"impulse":"57",
		"loyalty":"30",
		"scouting":"39",
		"camouflage":"31",
	},
	27: {
		"name":"Namazuo Toushirou",
		"type":"Wakizashi",
		"survival":"35",
		"impact":"45",
		"leadership":"45",
		"mobility":"48",
		"impulse":"40",
		"loyalty":"47",
		"scouting":"52",
		"camouflage":"46",
	},
	29: {
		"name":"Honebami Toushirou",
		"type":"Wakizashi",
		"survival":"41",
		"impact":"47",
		"leadership":"48",
		"mobility":"54",
		"impulse":"36",
		"loyalty":"49",
		"scouting":"49",
		"camouflage":"43",
	},
	31: {
		"name":"Hirano Toushirou",
		"type":"Tantou",
		"survival":"34",
		"impact":"32",
		"leadership":"45",
		"mobility":"56",
		"impulse":"30",
		"loyalty":"37",
		"scouting":"48",
		"camouflage":"38",
	},
	32: {
		"name":"Hirano Toushirou Kiwame",
		"type":"Tantou",
		"survival":"55",
		"impact":"90",
		"leadership":"78",
		"mobility":"138",
		"impulse":"42",
		"loyalty":"50",
		"scouting":"115",
		"camouflage":"112",
	},
	33: {
		"name":"Atsushi Toushirou",
		"type":"Tantou",
		"survival":"36",
		"impact":"32",
		"leadership":"42",
		"mobility":"58",
		"impulse":"30",
		"loyalty":"35",
		"scouting":"47",
		"camouflage":"38",
	},
	34: {
		"name":"Atsushi Toushirou Kiwame",
		"type":"Tantou",
		"survival":"58",
		"impact":"87",
		"leadership":"84",
		"mobility":"125",
		"impulse":"44",
		"loyalty":"48",
		"scouting":"110",
		"camouflage":"108",
	},
	35: {
		"name":"Gotou Toushirou",
		"type":"Tantou",
		"survival":"37",
		"impact":"35",
		"leadership":"44",
		"mobility":"49",
		"impulse":"38",
		"loyalty":"37",
		"scouting":"51",
		"camouflage":"38",
	},
	36: {
		"name":"Gotou Toushirou Kiwame",
		"type":"Tantou",
		"survival":"??",
		"impact":"84",
		"leadership":"82",
		"mobility":"143",
		"impulse":"42",
		"loyalty":"50",
		"scouting":"??",
		"camouflage":"108",
	},
	37: {
		"name":"Shinano Toushirou",
		"type":"Tantou",
		"survival":"38",
		"impact":"27",
		"leadership":"44",
		"mobility":"51",
		"impulse":"30",
		"loyalty":"35",
		"scouting":"52",
		"camouflage":"44",
	},
	39: {
		"name":"Maeda Toushirou",
		"type":"Tantou",
		"survival":"36",
		"impact":"31",
		"leadership":"41",
		"mobility":"52",
		"impulse":"30",
		"loyalty":"37",
		"scouting":"48",
		"camouflage":"38",
	},
	40: {
		"name":"Maeda Toushirou Kiwame",
		"type":"Tantou",
		"survival":"57",
		"impact":"81",
		"leadership":"83",
		"mobility":"130",
		"impulse":"39",
		"loyalty":"47",
		"scouting":"112",
		"camouflage":"118",
	},
	41: {
		"name":"Akita Toushirou",
		"type":"Tantou",
		"survival":"33",
		"impact":"30",
		"leadership":"42",
		"mobility":"52",
		"impulse":"33",
		"loyalty":"38",
		"scouting":"46",
		"camouflage":"38",
	},
	42: {
		"name":"Akita Toushirou Kiwame",
		"type":"Tantou",
		"survival":"59",
		"impact":"82",
		"leadership":"83",
		"mobility":"140",
		"impulse":"39",
		"loyalty":"52",
		"scouting":"113",
		"camouflage":"110",
	},
	43: {
		"name":"Hakata Toushirou",
		"type":"Tantou",
		"survival":"35",
		"impact":"30",
		"leadership":"38",
		"mobility":"64",
		"impulse":"31",
		"loyalty":"33",
		"scouting":"41",
		"camouflage":"38",
	},
	44: {
		"name":"Hakata Toushirou Kiwame",
		"type":"Tantou",
		"survival":"54",
		"impact":"85",
		"leadership":"74",
		"mobility":"145",
		"impulse":"35",
		"loyalty":"49",
		"scouting":"122",
		"camouflage":"112",
	},
	45: {
		"name":"Midare Toushirou",
		"type":"Tantou",
		"survival":"35",
		"impact":"31",
		"leadership":"40",
		"mobility":"55",
		"impulse":"30",
		"loyalty":"35",
		"scouting":"49",
		"camouflage":"39",
	},
	46: {
		"name":"Midare Toushirou Kiwame",
		"type":"Tantou",
		"survival":"55",
		"impact":"86",
		"leadership":"76",
		"mobility":"138",
		"impulse":"38",
		"loyalty":"58",
		"scouting":"114",
		"camouflage":"105",
	},
	47: {
		"name":"Gokotai",
		"type":"Tantou",
		"survival":"33",
		"impact":"27",
		"leadership":"39",
		"mobility":"58",
		"impulse":"29",
		"loyalty":"40",
		"scouting":"48",
		"camouflage":"39",
	},
	48: {
		"name":"Gokotai Kiwame",
		"type":"Tantou",
		"survival":"52",
		"impact":"86",
		"leadership":"75",
		"mobility":"142",
		"impulse":"38",
		"loyalty":"50",
		"scouting":"115",
		"camouflage":"120",
	},
	49: {
		"name":"Yagen Toushirou",
		"type":"Tantou",
		"survival":"34",
		"impact":"28",
		"leadership":"42",
		"mobility":"53",
		"impulse":"31",
		"loyalty":"40",
		"scouting":"47",
		"camouflage":"39",
	},
	50: {
		"name":"Yagen Toushirou Kiwame",
		"type":"Tantou",
		"survival":"58",
		"impact":"89",
		"leadership":"79",
		"mobility":"135",
		"impulse":"36",
		"loyalty":"42",
		"scouting":"119",
		"camouflage":"119",
	},
	51: {
		"name":"Houchou Toushirou",
		"type":"Tantou",
		"survival":"32",
		"impact":"34",
		"leadership":"40",
		"mobility":"48",
		"impulse":"35",
		"loyalty":"40",
		"scouting":"52",
		"camouflage":"45",
	},
	53: {
		"name":"Ookanehira",
		"type":"Tachi",
		"survival":"63",
		"impact":"75",
		"leadership":"70",
		"mobility":"38",
		"impulse":"58",
		"loyalty":"43",
		"scouting":"32",
		"camouflage":"27",
	},
	55: {
		"name":"Uguisumaru",
		"type":"Tachi",
		"survival":"64",
		"impact":"71",
		"leadership":"69",
		"mobility":"37",
		"impulse":"55",
		"loyalty":"28",
		"scouting":"38",
		"camouflage":"33",
	},
	57: {
		"name":"Akashi Kuniyuki",
		"type":"Tachi",
		"survival":"56",
		"impact":"63",
		"leadership":"67",
		"mobility":"49",
		"impulse":"47",
		"loyalty":"26",
		"scouting":"41",
		"camouflage":"36",
	},
	59: {
		"name":"Hotarumaru",
		"type":"Oodachi",
		"survival":"73",
		"impact":"81",
		"leadership":"74",
		"mobility":"18",
		"impulse":"60",
		"loyalty":"29",
		"scouting":"18",
		"camouflage":"28",
	},
	61: {
		"name":"Aizen Kunitoshi",
		"type":"Tantou",
		"survival":"35",
		"impact":"27",
		"leadership":"38",
		"mobility":"61",
		"impulse":"32",
		"loyalty":"39",
		"scouting":"47",
		"camouflage":"39",
	},
	62: {
		"name":"Aizen Kunitoshi Kiwame",
		"type":"Tantou",
		"survival":"56",
		"impact":"84",
		"leadership":"76",
		"mobility":"143",
		"impulse":"39",
		"loyalty":"50",
		"scouting":"115",
		"camouflage":"116",
	},
	63: {
		"name":"Sengo Muramasa",
		"type":"Uchigatana",
		"survival":"57",
		"impact":"73",
		"leadership":"66",
		"mobility":"31",
		"impulse":"59",
		"loyalty":"40",
		"scouting":"40",
		"camouflage":"25",
	},
	65: {
		"name":"Tonbokiri",
		"type":"Yari",
		"survival":"73",
		"impact":"76",
		"leadership":"63",
		"mobility":"27",
		"impulse":"63",
		"loyalty":"30",
		"scouting":"21",
		"camouflage":"33",
	},
	67: {
		"name":"Monoyoshi Sadamune",
		"type":"Wakizashi",
		"survival":"48",
		"impact":"41",
		"leadership":"60",
		"mobility":"53",
		"impulse":"53",
		"loyalty":"50",
		"scouting":"51",
		"camouflage":"30",
	},
	69: {
		"name":"Taikogane Sadamune",
		"type":"Tantou",
		"survival":"34",
		"impact":"31",
		"leadership":"44",
		"mobility":"58",
		"impulse":"31",
		"loyalty":"42",
		"scouting":"55",
		"camouflage":"39",
	},
	71: {
		"name":"Kikkou Sadamune",
		"type":"Uchigatana",
		"survival":"56",
		"impact":"54",
		"leadership":"55",
		"mobility":"47",
		"impulse":"53",
		"loyalty":"37",
		"scouting":"42",
		"camouflage":"40",
	},
	73: {
		"name":"Shokudaikiri Mitsutada",
		"type":"Tachi",
		"survival":"65",
		"impact":"73",
		"leadership":"72",
		"mobility":"34",
		"impulse":"53",
		"loyalty":"30",
		"scouting":"37",
		"camouflage":"30",
	},
	79: {
		"name":"Kousetsu Samonji",
		"type":"Tachi",
		"survival":"65",
		"impact":"72",
		"leadership":"70",
		"mobility":"37",
		"impulse":"57",
		"loyalty":"30",
		"scouting":"35",
		"camouflage":"32",
	},
	81: {
		"name":"Souza Samonji",
		"type":"Uchigatana",
		"survival":"42",
		"impact":"53",
		"leadership":"47",
		"mobility":"46",
		"impulse":"49",
		"loyalty":"30",
		"scouting":"42",
		"camouflage":"39",
	},
	83: {
		"name":"Sayo Samonji",
		"type":"Tantou",
		"survival":"39",
		"impact":"33",
		"leadership":"44",
		"mobility":"49",
		"impulse":"30",
		"loyalty":"42",
		"scouting":"47",
		"camouflage":"39",
	},
	84: {
		"name":"Sayo Samonji Kiwame",
		"type":"Tantou",
		"survival":"60",
		"impact":"92",
		"leadership":"80",
		"mobility":"126",
		"impulse":"39",
		"loyalty":"42",
		"scouting":"112",
		"camouflage":"108",
	},
	85: {
		"name":"Kashuu Kiyomitsu",
		"type":"Uchigatana",
		"survival":"43",
		"impact":"55",
		"leadership":"50",
		"mobility":"51",
		"impulse":"50",
		"loyalty":"41",
		"scouting":"46",
		"camouflage":"42",
	},
	87: {
		"name":"Yamatonokami Yasusada",
		"type":"Uchigatana",
		"survival":"47",
		"impact":"56",
		"leadership":"50",
		"mobility":"49",
		"impulse":"49",
		"loyalty":"38",
		"scouting":"43",
		"camouflage":"39",
	},
	89: {
		"name":"Kasen Kanesada",
		"type":"Uchigatana",
		"survival":"46",
		"impact":"59",
		"leadership":"50",
		"mobility":"50",
		"impulse":"51",
		"loyalty":"30",
		"scouting":"42",
		"camouflage":"39",
	},
	91: {
		"name":"Izuminokami Kanesada",
		"type":"Uchigatana",
		"survival":"64",
		"impact":"70",
		"leadership":"69",
		"mobility":"36",
		"impulse":"56",
		"loyalty":"35",
		"scouting":"38",
		"camouflage":"31",
	},
	93: {
		"name":"Mutsunokami Yoshiyuki",
		"type":"Uchigatana",
		"survival":"47",
		"impact":"61",
		"leadership":"47",
		"mobility":"47",
		"impulse":"53",
		"loyalty":"34",
		"scouting":"44",
		"camouflage":"40",
	},
	95: {
		"name":"Yamanbagiri Kunihiro",
		"type":"Uchigatana",
		"survival":"44",
		"impact":"58",
		"leadership":"49",
		"mobility":"52",
		"impulse":"55",
		"loyalty":"35",
		"scouting":"45",
		"camouflage":"41",
	},
	97: {
		"name":"Yamabushi Kunihiro",
		"type":"Tachi",
		"survival":"64",
		"impact":"72",
		"leadership":"66",
		"mobility":"37",
		"impulse":"52",
		"loyalty":"28",
		"scouting":"34",
		"camouflage":"30",
	},
	99: {
		"name":"Horikawa Kunihiro",
		"type":"Wakizashi",
		"survival":"37",
		"impact":"47",
		"leadership":"43",
		"mobility":"50",
		"impulse":"36",
		"loyalty":"45",
		"scouting":"53",
		"camouflage":"46",
	},
	101: {
		"name":"Hachisuka Kotetsu",
		"type":"Uchigatana",
		"survival":"51",
		"impact":"60",
		"leadership":"53",
		"mobility":"52",
		"impulse":"54",
		"loyalty":"31",
		"scouting":"44",
		"camouflage":"41",
	},
	103: {
		"name":"Urashima Kotetsu",
		"type":"Wakizashi",
		"survival":"45",
		"impact":"44",
		"leadership":"50",
		"mobility":"42",
		"impulse":"47",
		"loyalty":"40",
		"scouting":"53",
		"camouflage":"39",
	},
	105: {
		"name":"Nagasone Kotetsu",
		"type":"Uchigatana",
		"survival":"57",
		"impact":"68",
		"leadership":"53",
		"mobility":"42",
		"impulse":"56",
		"loyalty":"30",
		"scouting":"42",
		"camouflage":"39",
	},
	107: {
		"name":"Higekiri",
		"type":"Tachi",
		"survival":"51",
		"impact":"61",
		"leadership":"60",
		"mobility":"32",
		"impulse":"50",
		"loyalty":"32",
		"scouting":"33",
		"camouflage":"23",
	},
	108: {
		"name":"Higekiri",
		"type":"Tachi",
		"survival":"52",
		"impact":"63",
		"leadership":"64",
		"mobility":"33",
		"impulse":"51",
		"loyalty":"34",
		"scouting":"34",
		"camouflage":"24",
	},
	109: {
		"name":"Higekiri",
		"type":"Tachi",
		"survival":"54",
		"impact":"65",
		"leadership":"67",
		"mobility":"37",
		"impulse":"53",
		"loyalty":"36",
		"scouting":"38",
		"camouflage":"25",
	},
	110: {
		"name":"Higekiri",
		"type":"Tachi",
		"survival":"56",
		"impact":"70",
		"leadership":"70",
		"mobility":"38",
		"impulse":"55",
		"loyalty":"38",
		"scouting":"43",
		"camouflage":"26",
	},
	112: {
		"name":"Hizamaru",
		"type":"Tachi",
		"survival":"51",
		"impact":"60",
		"leadership":"60",
		"mobility":"38",
		"impulse":"49",
		"loyalty":"32",
		"scouting":"27",
		"camouflage":"30",
	},
	113: {
		"name":"Hizamaru",
		"type":"Tachi",
		"survival":"51",
		"impact":"63",
		"leadership":"61",
		"mobility":"43",
		"impulse":"51",
		"loyalty":"34",
		"scouting":"28",
		"camouflage":"33",
	},
	114: {
		"name":"Hizamaru",
		"type":"Tachi",
		"survival":"56",
		"impact":"69",
		"leadership":"69",
		"mobility":"51",
		"impulse":"54",
		"loyalty":"36",
		"scouting":"29",
		"camouflage":"37",
	},
	116: {
		"name":"Ookurikara",
		"type":"Uchigatana",
		"survival":"59",
		"impact":"69",
		"leadership":"69",
		"mobility":"33",
		"impulse":"56",
		"loyalty":"28",
		"scouting":"34",
		"camouflage":"31",
	},
	118: {
		"name":"Heshikiri Hasebe",
		"type":"Uchigatana",
		"survival":"51",
		"impact":"61",
		"leadership":"48",
		"mobility":"57",
		"impulse":"54",
		"loyalty":"33",
		"scouting":"43",
		"camouflage":"38",
	},
	120: {
		"name":"Fudou Yukimitsu",
		"type":"Tantou",
		"survival":"36",
		"impact":"34",
		"leadership":"40",
		"mobility":"55",
		"impulse":"33",
		"loyalty":"42",
		"scouting":"49",
		"camouflage":"37",
	},
	122: {
		"name":"Shishiou",
		"type":"Tachi",
		"survival":"59",
		"impact":"66",
		"leadership":"72",
		"mobility":"37",
		"impulse":"56",
		"loyalty":"28",
		"scouting":"33",
		"camouflage":"31",
	},
	124: {
		"name":"Kogarasumaru",
		"type":"Tachi",
		"survival":"70",
		"impact":"65",
		"leadership":"65",
		"mobility":"53",
		"impulse":"46",
		"loyalty":"35",
		"scouting":"40",
		"camouflage":"26",
	},
	128: {
		"name":"Doudanuki Masakuni",
		"type":"Uchigatana",
		"survival":"56",
		"impact":"69",
		"leadership":"65",
		"mobility":"33",
		"impulse":"55",
		"loyalty":"30",
		"scouting":"36",
		"camouflage":"28",
	},
	130: {
		"name":"Tsurumaru Kuninaga",
		"type":"Tachi",
		"survival":"62",
		"impact":"69",
		"leadership":"69",
		"mobility":"34",
		"impulse":"51",
		"loyalty":"32",
		"scouting":"33",
		"camouflage":"29",
	},
	132: {
		"name":"Taroutachi",
		"type":"Oodachi",
		"survival":"76",
		"impact":"82",
		"leadership":"77",
		"mobility":"17",
		"impulse":"61",
		"loyalty":"26",
		"scouting":"20",
		"camouflage":"31",
	},
	134: {
		"name":"Jiroutachi",
		"type":"Oodachi",
		"survival":"72",
		"impact":"84",
		"leadership":"80",
		"mobility":"16",
		"impulse":"58",
		"loyalty":"23",
		"scouting":"18",
		"camouflage":"35",
	},
	136: {
		"name":"Nihongou",
		"type":"Yari",
		"survival":"66",
		"impact":"72",
		"leadership":"50",
		"mobility":"51",
		"impulse":"64",
		"loyalty":"34",
		"scouting":"28",
		"camouflage":"33",
	},
	138: {
		"name":"Otegine",
		"type":"Yari",
		"survival":"60",
		"impact":"69",
		"leadership":"51",
		"mobility":"42",
		"impulse":"62",
		"loyalty":"32",
		"scouting":"40",
		"camouflage":"33",
	},
	// template
	0: {
		"name":"",
		"type":"",
		"survival":"",
		"impact":"",
		"leadership":"",
		"mobility":"",
		"impulse":"",
		"loyalty":"",
		"scouting":"",
		"camouflage":"",
	},
}